name: Daily Birthday Reminder

on:
  schedule:
    # 09:00 AM IST = 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  birthday-check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Birthday Reminder
        shell: cmd
        env:
          NTFY_TOPIC: tpGme3XOxG2iZ6Dd
        run: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%GITHUB_WORKSPACE%\birthday-reminder.ps1"
