name: Daily Birthday Reminder

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  birthday:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Birthday Reminder
        shell: cmd
        run: |
          powershell.exe -ExecutionPolicy Bypass -File birthday-reminder.ps1
