name: Daily Birthday Reminder

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  birthday-check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install BurntToast
        shell: powershell
        run: |
          Install-Module -Name BurntToast -Force -Scope CurrentUser -AllowClobber

      - name: Run Birthday Reminder
        shell: powershell
        run: |
          powershell.exe -ExecutionPolicy Bypass -File birthday-reminder.ps1
